### ISSUE TITLE
Setup On server

### ISSUE THREAD

**Issue by ASAPChiul** [ericz99/instagram-monitor#1]
Hello! I setup this on my server, i installed yarn, npm and nodejs, after i ran it, i edited the config and now it dosen't post to discord,
**

> [nodemon] starting `babel-node index.js`
> Loaded 0 proxies!
> [nodemon] clean exit - waiting for changes before restart

**
 only gives me that

Help would be appreciated, thanks :)

**Comment by ASAPChiul** [comment]
i also did the .env file and added a instagram login

**Comment by ericz99** [comment]
Hey, I have a new update coming soon. I'll also add a guide on how to setup on a server.

**Comment by ASAPChiul** [comment]
thanks!
