### ISSUE TITLE
Story working, posts not.

### ISSUE THREAD

**Issue by cookinggod** [ericz99/instagram-monitor#10]
New story found! however posts cannot be found.

**Comment by abramkremer** [comment]
Yupp I've noticed the same problem @cookinggod

**Comment by ericz99** [comment]
Hey, I managed to fix the issue for the stories monitor. But, I am currently running test to see if there's anymore error. Will probably push update by tomorrow.

**Comment by ericz99** [comment]
Hi, I removed story monitor for now. But, post monitor still work. If you getting proxy timeout then refer to the note in Readme file.
