### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ASAPChiul** [ericz99/instagram-monitor#2]
Hello! I made the monitor start up and now im getting this error

> root@vultr:~/instagram-monitor# yarn run start
> yarn run v1.17.3
> $ nodemon --exec babel-node index.js
> [nodemon] 1.19.1
> [nodemon] to restart at any time, enter `rs`
> [nodemon] watching: *.*
> [nodemon] starting `babel-node index.js`
> Loaded 81 proxies!
> Successfully logged into account!
> [18:12:52.219] [leshouses] [+] Started task!
> (node:9919) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'node' of undefined
>     at node (/root/instagram-monitor/libs/api/index.js:118:53)
>     at tryCatch (/root/instagram-monitor/node_modules/regenerator-runtime/runtime.js:45:40)
>     at Generator.invoke [as _invoke] (/root/instagram-monitor/node_modules/regenerator-runtime/runtime.js:271:22)
>     at Generator.prototype.(anonymous function) [as next] (/root/instagram-monitor/node_modules/regenerator-runtime/runtime.js:97:21)
>     at asyncGeneratorStep (/root/instagram-monitor/libs/api/index.js:18:103)
>     at _next (/root/instagram-monitor/libs/api/index.js:20:194)
>     at /root/instagram-monitor/libs/api/index.js:20:364
>     at new Promise (<anonymous>)
>     at /root/instagram-monitor/libs/api/index.js:20:97
>     at scrapeUserData (/root/instagram-monitor/libs/api/index.js:98:28)
>     at _callee$ (/root/instagram-monitor/libs/task/index.js:32:30)
>     at tryCatch (/root/instagram-monitor/node_modules/regenerator-runtime/runtime.js:45:40)
>     at Generator.invoke [as _invoke] (/root/instagram-monitor/node_modules/regenerator-runtime/runtime.js:271:22)
>     at Generator.prototype.(anonymous function) [as next] (/root/instagram-monitor/node_modules/regenerator-runtime/runtime.js:97:21)
>     at asyncGeneratorStep (/root/instagram-monitor/libs/task/index.js:28:103)
>     at _next (/root/instagram-monitor/libs/task/index.js:30:194)
> (node:9919) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:9919) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> (node:9919) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'node' of undefined
>     at node (/root/instagram-monitor/libs/api/index.js:118:53)
>     at tryCatch (/root/instagram-monitor/node_modules/regenerator-runtime/runtime.js:45:40)
>     at Generator.invoke [as _invoke] (/root/instagram-monitor/node_modules/regenerator-runtime/runtime.js:271:22)
>     at Generator.prototype.(anonymous function) [as next] (/root/instagram-monitor/node_modules/regenerator-runtime/runtime.js:97:21)
>     at asyncGeneratorStep (/root/instagram-monitor/libs/api/index.js:18:103)
>     at _next (/root/instagram-monitor/libs/api/index.js:20:194)
>     at /root/instagram-monitor/libs/api/index.js:20:364
>     at new Promise (<anonymous>)
>     at /root/instagram-monitor/libs/api/index.js:20:97
>     at scrapeUserData (/root/instagram-monitor/libs/api/index.js:98:28)
>     at _callee$ (/root/instagram-monitor/libs/task/index.js:32:30)
>     at tryCatch (/root/instagram-monitor/node_modules/regenerator-runtime/runtime.js:45:40)
>     at Generator.invoke [as _invoke] (/root/instagram-monitor/node_modules/regenerator-runtime/runtime.js:271:22)
>     at Generator.prototype.(anonymous function) [as next] (/root/instagram-monitor/node_modules/regenerator-runtime/runtime.js:97:21)
>     at asyncGeneratorStep (/root/instagram-monitor/libs/task/index.js:28:103)
>     at _next (/root/instagram-monitor/libs/task/index.js:30:194)
> (node:9919) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
> (node:9919) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'node' of undefined
>     at node (/root/instagram-monitor/libs/api/index.js:118:53)
>     at tryCatch (/root/instagram-monitor/node_modules/regenerator-runtime/runtime.js:45:40)
>     at Generator.invoke [as _invoke] (/root/instagram-monitor/node_modules/regenerator-runtime/runtime.js:271:22)
>     at Generator.prototype.(anonymous function) [as next] (/root/instagram-monitor/node_modules/regenerator-runtime/runtime.js:97:21)
>     at asyncGeneratorStep (/root/instagram-monitor/libs/api/index.js:18:103)
>     at _next (/root/instagram-monitor/libs/api/index.js:20:194)
>     at /root/instagram-monitor/libs/api/index.js:20:364
>     at new Promise (<anonymous>)
>     at /root/instagram-monitor/libs/api/index.js:20:97
>     at scrapeUserData (/root/instagram-monitor/libs/api/index.js:98:28)
>     at _callee$ (/root/instagram-monitor/libs/task/index.js:32:30)
>     at tryCatch (/root/instagram-monitor/node_modules/regenerator-runtime/runtime.js:45:40)
>     at Generator.invoke [as _invoke] (/root/instagram-monitor/node_modules/regenerator-runtime/runtime.js:271:22)
>     at Generator.prototype.(anonymous function) [as next] (/root/instagram-monitor/node_modules/regenerator-runtime/runtime.js:97:21)
>     at asyncGeneratorStep (/root/instagram-monitor/libs/task/index.js:28:103)
>     at _next (/root/instagram-monitor/libs/task/index.js:30:194)
> (node:9919) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)

Thanks in advance for your help :)

**Comment by ericz99** [comment]
do you have nodejs install on vultr?

**Comment by ASAPChiul** [comment]
yes

**Comment by ASAPChiul** [comment]
do i need to install anything more?

**Comment by ASAPChiul** [comment]
now i get a new error, C:\Users\loner\Documents\instagram-monitor>yarn run start
yarn run v1.17.3
$ nodemon --exec babel-node index.js
[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node index.js`
Loaded 25 proxies!
Successfully logged into account!
[12:40:40.607] [my username] [+] Started task!
Proxy timeout!
[12:40:41.722] [my username] [x] Restarting task...

**Comment by ericz99** [comment]
proxy timeout, meaning proxy dead. Task will automatically restart with new proxy in proxy pool.

**Comment by ericz99** [comment]
you need anything else?

**Comment by ASAPChiul** [comment]
i tried to use no proxies and it gave the same error
