### ISSUE TITLE
Im getting errorgettig error

### ISSUE THREAD

**Issue by MARIOpremiun** [ericz99/instagram-monitor#3]
[20:50:08.938] [cybersole] [x] Restarting task...

thats what it says over and over again im on 5000 dlelay and 25 dc proxies

**Comment by ericz99** [comment]
probably your provider is banned on instagram.

**Comment by ericz99** [comment]
try new proxies, if not, increase your delays. If you still need help, make new issue. Closing this one.

**Comment by MARIOpremiun** [comment]
i'm getting this error and then restarting task timeout proxy but when i
test my proxies on instagram it says ok

[image: Screen Shot 2019-09-11 at 15.17.02.png]

‫בתאריך יום ג׳, 10 בספט׳ 2019 ב-22:45 מאת ‪Eric‬‏ <‪notifications@github.com
‬‏>:‬
