### ISSUE TITLE
Getting other errors

### ISSUE THREAD

**Issue by MARIOpremiun** [ericz99/instagram-monitor#4]
<img width="722" alt="Screen Shot 2019-09-11 at 15 17 02" src="https://user-images.githubusercontent.com/54009865/64696888-3fb60b00-d4a8-11e9-839a-c2003cf8d4ed.png">
and then retarting task because of proxy timeout and when i test my proxies on insta it says ok

**Comment by ericz99** [comment]
When proxy timeout, it usually mean a temp ban, not an actual ban. Reason is because of your proxy provider. I'll have another update soon that will fix any error, and apparently the post doesn't have text. So i'll take care of these error soon.

**Comment by MARIOpremiun** [comment]
Thanks and another thing is about the twitter monitor im getting an error
too
[image: Screen Shot 2019-09-11 at 16.55.33.png]

‫בתאריך יום ד׳, 11 בספט׳ 2019 ב-16:41 מאת ‪Eric‬‏ <‪notifications@github.com
‬‏>:‬

**Comment by ericz99** [comment]
I can't see the screenshot.

**Comment by ericz99** [comment]
Closing issue now. If you have any other problems, simply create a new issue.
