### ISSUE TITLE
When is the update

### ISSUE THREAD

**Issue by MARIOpremiun** [ericz99/instagram-monitor#5]
Hey man, when you'll be fixing all the errors and can you send me your discord name so'll be able to contact you if i need help?

**Comment by ericz99** [comment]
Tonight.

**Comment by MARIOpremiun** [comment]
Ok thanks appreciate the fast replay

**Comment by ericz99** [comment]
Updating tmr, since I'm still working on my story monitor. But, definitely will be finish with this by tmr.

**Comment by ericz99** [comment]
hey, I updated the monitor, please run git pull to get the latest update build. Any errors or anything please open another issue. Closing this now..
