### ISSUE TITLE
Story monitor isnt working

### ISSUE THREAD

**Issue by MARIOpremiun** [ericz99/instagram-monitor#8]
Sorry for that much issues in one day but just to lyk the story monitor isn't working
And if im running it on a server how do i run it 24/7 can i use pm2? if u can tell me which command it will help

**Comment by ericz99** [comment]
hey, you gotta be more specific, saying story monitor isn't working, is not gonna help me solve the issue..

**Comment by MARIOpremiun** [comment]
Just nothing happens when i post a story

**Comment by ericz99** [comment]
But, is there any error?

**Comment by MARIOpremiun** [comment]
Nope. Nothing

**Comment by ericz99** [comment]
![image](https://user-images.githubusercontent.com/34465814/65263112-d5b9e900-dad9-11e9-8c41-6313d9187fbe.png)

Fixed it, uploading shortly.

**Comment by MARIOpremiun** [comment]
Thanks bro and how do i run it non stop?

**Comment by ericz99** [comment]
just run git pull to get the latest build.

**Comment by ericz99** [comment]
closing issue now, if you want to run this forever, please go research yourself.
